name: Run Jaffle Shop dlt Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run dlt pipeline
        env:
          DLT_SECRETS__DESTINATION__DUCKDB__CREDENTIALS: "duckdb:///jaffle_shop_incremental.duckdb"
        run: |
          python pipeline.py

      - name: Upload database artifact
        uses: actions/upload-artifact@v3
        with:
          name: jaffle-shop-database
          path: jaffle_shop_incremental.duckdb
          retention-days: 30
